---
  apiVersion: v1
  data:
    tls.crt: ""
    tls.key: ""
  kind: Secret
  metadata:
    name: cass-operator-webhook-config
    namespace: test-operator
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: cassandradatacenter-webhook-registration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: cassandradatacenter-webhook-service
      namespace: test-operator
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: cassandradatacenter-webhook.cassandra.datastax.com
  rules:
  - apiGroups:
    - cassandra.datastax.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandradatacenters
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: cass-operator-webhook
  name: cassandradatacenter-webhook-service
  namespace: test-operator
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    name: cass-operator
