apiVersion: v1
kind: ServiceAccount
metadata:
  #namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-preserve-crd
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
