/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/riptano/dse-operator/operator/pkg/apis/datastax/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDseDatacenters implements DseDatacenterInterface
type FakeDseDatacenters struct {
	Fake *FakeDatastaxV1alpha1
	ns   string
}

var dsedatacentersResource = schema.GroupVersionResource{Group: "datastax.com", Version: "v1alpha1", Resource: "dsedatacenters"}

var dsedatacentersKind = schema.GroupVersionKind{Group: "datastax.com", Version: "v1alpha1", Kind: "DseDatacenter"}

// Get takes name of the dseDatacenter, and returns the corresponding dseDatacenter object, and an error if there is any.
func (c *FakeDseDatacenters) Get(name string, options v1.GetOptions) (result *v1alpha1.DseDatacenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dsedatacentersResource, c.ns, name), &v1alpha1.DseDatacenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DseDatacenter), err
}

// List takes label and field selectors, and returns the list of DseDatacenters that match those selectors.
func (c *FakeDseDatacenters) List(opts v1.ListOptions) (result *v1alpha1.DseDatacenterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dsedatacentersResource, dsedatacentersKind, c.ns, opts), &v1alpha1.DseDatacenterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DseDatacenterList{ListMeta: obj.(*v1alpha1.DseDatacenterList).ListMeta}
	for _, item := range obj.(*v1alpha1.DseDatacenterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dseDatacenters.
func (c *FakeDseDatacenters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dsedatacentersResource, c.ns, opts))

}

// Create takes the representation of a dseDatacenter and creates it.  Returns the server's representation of the dseDatacenter, and an error, if there is any.
func (c *FakeDseDatacenters) Create(dseDatacenter *v1alpha1.DseDatacenter) (result *v1alpha1.DseDatacenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dsedatacentersResource, c.ns, dseDatacenter), &v1alpha1.DseDatacenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DseDatacenter), err
}

// Update takes the representation of a dseDatacenter and updates it. Returns the server's representation of the dseDatacenter, and an error, if there is any.
func (c *FakeDseDatacenters) Update(dseDatacenter *v1alpha1.DseDatacenter) (result *v1alpha1.DseDatacenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dsedatacentersResource, c.ns, dseDatacenter), &v1alpha1.DseDatacenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DseDatacenter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDseDatacenters) UpdateStatus(dseDatacenter *v1alpha1.DseDatacenter) (*v1alpha1.DseDatacenter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dsedatacentersResource, "status", c.ns, dseDatacenter), &v1alpha1.DseDatacenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DseDatacenter), err
}

// Delete takes name of the dseDatacenter and deletes it. Returns an error if one occurs.
func (c *FakeDseDatacenters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dsedatacentersResource, c.ns, name), &v1alpha1.DseDatacenter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDseDatacenters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dsedatacentersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DseDatacenterList{})
	return err
}

// Patch applies the patch and returns the patched dseDatacenter.
func (c *FakeDseDatacenters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DseDatacenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dsedatacentersResource, c.ns, name, pt, data, subresources...), &v1alpha1.DseDatacenter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DseDatacenter), err
}
