/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/riptano/dse-operator/operator/pkg/apis/datastax/v1alpha1"
	scheme "github.com/riptano/dse-operator/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DseDatacentersGetter has a method to return a DseDatacenterInterface.
// A group's client should implement this interface.
type DseDatacentersGetter interface {
	DseDatacenters(namespace string) DseDatacenterInterface
}

// DseDatacenterInterface has methods to work with DseDatacenter resources.
type DseDatacenterInterface interface {
	Create(*v1alpha1.DseDatacenter) (*v1alpha1.DseDatacenter, error)
	Update(*v1alpha1.DseDatacenter) (*v1alpha1.DseDatacenter, error)
	UpdateStatus(*v1alpha1.DseDatacenter) (*v1alpha1.DseDatacenter, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DseDatacenter, error)
	List(opts v1.ListOptions) (*v1alpha1.DseDatacenterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DseDatacenter, err error)
	DseDatacenterExpansion
}

// dseDatacenters implements DseDatacenterInterface
type dseDatacenters struct {
	client rest.Interface
	ns     string
}

// newDseDatacenters returns a DseDatacenters
func newDseDatacenters(c *DatastaxV1alpha1Client, namespace string) *dseDatacenters {
	return &dseDatacenters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dseDatacenter, and returns the corresponding dseDatacenter object, and an error if there is any.
func (c *dseDatacenters) Get(name string, options v1.GetOptions) (result *v1alpha1.DseDatacenter, err error) {
	result = &v1alpha1.DseDatacenter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dsedatacenters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DseDatacenters that match those selectors.
func (c *dseDatacenters) List(opts v1.ListOptions) (result *v1alpha1.DseDatacenterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DseDatacenterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dsedatacenters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dseDatacenters.
func (c *dseDatacenters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dsedatacenters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dseDatacenter and creates it.  Returns the server's representation of the dseDatacenter, and an error, if there is any.
func (c *dseDatacenters) Create(dseDatacenter *v1alpha1.DseDatacenter) (result *v1alpha1.DseDatacenter, err error) {
	result = &v1alpha1.DseDatacenter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dsedatacenters").
		Body(dseDatacenter).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dseDatacenter and updates it. Returns the server's representation of the dseDatacenter, and an error, if there is any.
func (c *dseDatacenters) Update(dseDatacenter *v1alpha1.DseDatacenter) (result *v1alpha1.DseDatacenter, err error) {
	result = &v1alpha1.DseDatacenter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dsedatacenters").
		Name(dseDatacenter.Name).
		Body(dseDatacenter).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *dseDatacenters) UpdateStatus(dseDatacenter *v1alpha1.DseDatacenter) (result *v1alpha1.DseDatacenter, err error) {
	result = &v1alpha1.DseDatacenter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dsedatacenters").
		Name(dseDatacenter.Name).
		SubResource("status").
		Body(dseDatacenter).
		Do().
		Into(result)
	return
}

// Delete takes name of the dseDatacenter and deletes it. Returns an error if one occurs.
func (c *dseDatacenters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dsedatacenters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dseDatacenters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dsedatacenters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dseDatacenter.
func (c *dseDatacenters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DseDatacenter, err error) {
	result = &v1alpha1.DseDatacenter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dsedatacenters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
