// Copyright DataStax, Inc.
// Please see the included license file for details.

// NOTE: Boilerplate only.  Ignore this file.

// Package v1beta1 contains API Schema definitions for the cassandra v1beta1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=cassandra.datastax.com
package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: "cassandra.datastax.com", Version: "v1beta1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
)

// everything below here wasn't generated by operator-sdk, but the sample-controller project has it in register.go,
// and we need it for client-gen
// see https://github.com/kubernetes/sample-controller/blob/master/pkg/apis/samplecontroller/v1alpha1/register.go

// AddToScheme is a global function that registers this API group & version to a scheme
var AddToScheme = SchemeBuilder.AddToScheme

// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}
