# Default values
cassOperatorNamespace: cass-operator
serviceAccountName: cass-operator
roleName: cass-operator
roleBindingName: cass-operator
deploymentName: cass-operator
deploymentReplicas: 1
image: "datastax/cass-operator:1.0.0"
imagePullPolicy: IfNotPresent
