# Default values
clusterWideInstall: false
serviceAccountName: cass-operator
roleName: cass-operator
roleBindingName: cass-operator
webhookClusterRoleName: cass-operator-webhook
webhookClusterRoleBindingName: cass-operator-webhook
deploymentName: cass-operator
deploymentReplicas: 1
image: "datastax/cass-operator:1.4.1"
imagePullPolicy: IfNotPresent
