apiVersion: storage.k8s.io/v2
kind: StorageClass
metadata:
  name: server-storage
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: ibm.io/ibmc-block
parameters:
  zone: "dal12"
  region: "us-south"
  type: "Endurance"
  iopsPerGB: "4"
  sizeRange: "[4-20]Gi"
reclaimPolicy: "Delete"