apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server-storage
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: ibm.io/ibmc-block
parameters:
  classVersion: "2"
  zone: "dal12"
  region: "us-south"
  type: "Endurance"
  iopsPerGB: "2"
  sizeRange: "[20-12000]Gi"
reclaimPolicy: "Delete"