kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cass-operator
  namespace: {{ .Values.cassOperatorNamespace }}
subjects:
- kind: ServiceAccount
  name: cass-operator
roleRef:
  kind: Role
  name: cass-operator
  apiGroup: rbac.authorization.k8s.io
