apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cassandradatacenter-webhook-registration"
webhooks:
- name: "cassandradatacenter-webhook.cassandra.datastax.com"
  rules:
  - apiGroups: ["cassandra.datastax.com"]
    apiVersions: ["v1beta1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["cassandradatacenters"]
    {{- if semverCompare ">= 1.14-0" .Capabilities.KubeVersion.GitVersion }}
    scope: "*"
    {{- end }}
  clientConfig:
    service:
      name: "cassandradatacenter-webhook-service"
      namespace: {{ .Release.Namespace }}
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
  {{- if semverCompare ">= 1.14-0" .Capabilities.KubeVersion.GitVersion }}
  admissionReviewVersions: ["v1beta1"]
  timeoutSeconds: 10
  {{- end }}
  failurePolicy: "Ignore"
  {{- if semverCompare ">= 1.15-0" .Capabilities.KubeVersion.GitVersion }}
  matchPolicy: "Equivalent"
  {{- end }}
  sideEffects: None
