// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha2

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenter":       schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenter(ref),
		"github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterSpec":   schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenterSpec(ref),
		"github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterStatus": schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenterStatus(ref),
	}
}

func schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenter(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CassandraDatacenter is the Schema for the cassandradatacenters API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterSpec", "github.com/riptano/dse-operator/operator/pkg/apis/cassandra/v1alpha2.CassandraDatacenterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CassandraDatacenterSpec defines the desired state of CassandraDatacenter",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_cassandra_v1alpha2_CassandraDatacenterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CassandraDatacenterStatus defines the observed state of CassandraDatacenter",
				Type:        []string{"object"},
			},
		},
	}
}
