name: Mage testing
on:
  push:
    branches:    
      - KO-359-mage-gh-action-no-sudo
jobs:
  test_mage:
    name: Test Mage
    runs-on: ubuntu-latest
    env:
      GOROOT: /usr/local/go1.13
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install Mage
        run: |
          cd /tmp
          wget https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz
          tar -xvf mage_1.9.0_Linux-64bit.tar.gz
          sudo mkdir -p ~/go/bin
          sudo mkdir -p ~/go/pkg/mod/cache
          sudo mv mage ~/go/bin/mage
          sudo chmod +x ~/go/bin/mage
      - name: List targets
        run: |
          go list -tags=mage -e -f '{{join .GoFiles "||"}}'
