name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release_cass_operator:
    name: Release Cass Operator
    runs-on: ubuntu-latest
    env:
      # This is needed to workaround an issue where skopeo vomits out an
      # error "mkdir /run/containers: permission denied" when performing
      # login.
      XDG_RUNTIME_DIR: /tmp
      ECR_REPO: ${{ secrets.ECR_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Login Skopeo DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASS }}" | skopeo login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin docker.io
      - name: Login Skopeo ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_SECRET }}
        run: aws ecr get-login-password --region us-east-1 | skopeo login -u AWS --password-stdin ${ECR_REPO}
      - name: Login Skopeo Red Hat
        env:
          REDHAT_REPO: ${{ secrets.REDHAT_REPO }}
          REDHAT_SECRET: ${{ secrets.REDHAT_SECRET }}
        run: docker login -u unused --password "$REDHAT_SECRET" $REDHAT_REPO
      - name: Publish to Dockerhub
        run: |
          ./scripts/push-release.sh
