name: Testing Workflow
on: pull_request
jobs:
  build_operator_docker:
    name: Build Cass Operator Docker Image
    runs-on: ubuntu-latest
    env:
      GOPATH: /go
      GOROOT: /usr/local/go1.13
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install Mage
        run: |
          cd /tmp
          wget https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz
          tar -xvf mage_1.9.0_Linux-64bit.tar.gz
          sudo mkdir -p /go/bin
          sudo mv mage /go/bin
          sudo chmod +x /go/bin/mage
      - name: Cache go pkgs
        uses: actions/cache@v1
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache docker
        uses: actions/cache@v1
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-go-${{ hashFiles('/var/lib/docker/image/overlay2/layerdb/sha256/*') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Build docker
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          chmomd -R 777 .
          mage operator:buildDocker
      - name: Deploy to ECR
        env: 
          MO_ECR_ID: ${{ secrets.ECR_ID }}
          MO_ECR_SECRET: ${{ secrets.ECR_SECRET }}
          MO_ECR_REPO: ${{ secrets.ECR_REPO }}
        run: |
          export MO_TAGS=$(cat ./build/tagsToPush.txt)
          mage operator:deployToECR
