name: Testing Workflow
on: pull_request
jobs:
  build_operator_docker:
    name: Build Cass Operator Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: install Go 1.13
        run: |
          cd /tmp
          wget https://dl.google.com/go/go1.13.9.linux-amd64.tar.gz
          tar -xvf go1.13.9.linux-amd64.tar.gz
          sudo mv go /usr/local
      - name: Build docker
        run: |
          mage operator:buildDocker

