name: Testing Workflow
on: pull_request
jobs:
  build_operator_docker:
    name: Build Cass Operator Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install Mage
        run: |
          cd /tmp
          wget https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz
          tar -xvf mage_1.9.0_Linux-64bit.tar.gz
          sudo mkdir -p /go/bin
          sudo mv mage /go/bin
          sudo chmod +x /go/bin/mage
      - name: Build docker
        env:
          GOPATH: /go
          GOROOT: /usr/local/go1.13
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          go version
          go env
          ls -lrt
          mage

